### ISSUE TITLE
Include USA Remote Automatic Weather Stations (RAWS) climate archive

### ISSUE THREAD

**Issue by hansthompson** [rich-iannone/stationaRy#1]
Looove this package.  Any chance you are working including the RAWS data as well?

**Comment by rich-iannone** [comment]
Yes! Here's what I really want to make available:
- extra met fields from NCDC
- the U.S. AQ data (e.g. PM, gases, VOCs)
- the RAWS data

I'll look at the RAWS stuff tonight. How is it usually accessed?

**Comment by hansthompson** [comment]
I've been trying to find a good source. You can get it in small doses at http://www.raws.dri.edu/ but I've contacted my local noaa office and they have access to all of it through the aforementioned site without restriction so there is access if you are an agency.

**Comment by rich-iannone** [comment]
@hansthompson thanks again for looking into this! Until there is a full, publicly-available dataset, I'll hold off on this addition.
