### ISSUE TITLE
Downloaded 0 bytes Error in if (file.exists(data_files[i])) { : argument is of length zero 

### ISSUE THREAD

**Issue by cebaraldi** [rich-iannone/stationaRy#13]
I am collecting weather data in a loop from several stations by country. But sometimes there seems to be no data and my script breaks. Could you suggest what to do to continue the loop in such cases?

Regards, 
Claudio

get_isd_station_data(station_id = "64080-99999",
                     startyear = 2014,
                     endyear = 2015)
trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2013/064080-99999-2013.gz'
downloaded 0 bytes
trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2014/064080-99999-2014.gz'
downloaded 0 bytes
trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2015/064080-99999-2015.gz'
downloaded 0 bytes
Error in if (file.exists(data_files[i])) { : argument is of length zero

**Comment by rich-iannone** [comment]
Hi Claudio... I'm running into the same problems and my thinking is that there are server problems or perhaps a relocation of files. I'll investigate this and change download path in the source.

**Comment by cebaraldi** [comment]
Hello Richard

Thanks for your quick answer.

Maybe these are server problems, but is there a way to catch these errors
by returning an status code? One then could react to this code and proceed
with a loop. This code could represent a couple of situations. I don't know
what could all go wrong, for instance: empty file, server fatigue, capacity
overload, and so on. If nothing else is detected, it would return success.

By the way, I enjoy your stationaRy package a lot!

Cheers, Claudio

**Comment by cmgreenjr** [comment]
Hello Rich,

First I want to thank you for your stationaRy package.  I have high hopes
for using it to pull weather data, however I am having the same problems as
Claudio.  Have you made any discoveries on what is happening?

Thank you Sir,

Charles

**Comment by cebaraldi** [comment]
Hi Richard,

I have done an analysis of a specific weather station in Belgium. Its name is OOSTENDE (PIER) and has data available for the two periods of 1946-1956 and 1973-2006. 

The results are summarized after the three lines that create the variable b1. 4 runs have status OK, 3 runs are NotOK(=NOK). It seems that the R function get_isd_station_data has difficulties to read data when there is a gap in time. Between 1956 and 1973 is a gap. Maybe if you concentrate on this weather station with its gap, you can pin down the problem and solve it?

Regards,
Claudio

library(stationaRy)
library(dplyr)
rm(list=ls())

n <- "OOSTENDE (PIER)"

# Available years/files: 1946-1956, 1973-2006

b1 <- get_isd_stations() %>% 
  select_isd_station(name=n,number=1) %>%
  get_isd_station_data(startyear=1956,endyear=1973)

# startyear  endyear  records  status

# 1956       1956        545      OK

# 1973       1973        2047     OK

# 1956       1972        545      OK

# 1956       1973        545      NOK

# 1970       1973           -        NOK

# 1971       1973           -        NOK

# 1972       1973         545      OK
