### ISSUE TITLE
Can't find "file.size" function

### ISSUE THREAD

**Issue by ghost** [rich-iannone/stationaRy#14]
Hi,
when i run this code
<code>met_data <- get_isd_station_data(station_id = "165220-99999",
                                 startyear = 2009,
                                 endyear = 2015) </code>
the library starts to get files from ftp.ncdc.noaa.gov correctly, but at the endof the proces i get this message
<code>can't find file.size function</code>

**Comment by rich-iannone** [comment]
The function works for me so it might be an older version of the code with a non-working part. Please download the latest development version with `devtools::install_github('rich-iannone/stationaRy')` and try this again. Let me know if that doesn't work.

**Comment by ghost** [comment]
i just installed the package from github and now it's ok. thank you
