### ISSUE TITLE
tests fail with dev version of readr

### ISSUE THREAD

**Issue by hadley** [rich-iannone/stationaRy#16]
```
checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  1 710040 99999 CYPRESS BOWL FREESTYLE      CA       49.400 -123.2   969  2007
  2 715620 99999 CYPRESS BOWL SNOWBOARD      CA       49.383 -123.2  1180  2010
  3 716930 99999     CYPRESS BOWL SOUTH      CA       49.383 -123.2   886  2007
  Variables not shown: end (dbl), gmt_offset (dbl), time_zone_id (chr),
    country_name (chr), country_code (chr), iso3166_2_subd (chr), fips10_4_subd
    (chr)
  testthat results ================================================================
  OK: 30 SKIPPED: 0 FAILED: 2
  1. Error: get_isd_station_data returns correct number of columns 
  2. Error: error messages are provided in certain situations 

  Error: testthat unit tests failed
  Execution halted
```

I did a bit of exploration, and it looks like this is because readr now longer guesses that strings with leading 0s are integers.  You can fix it by manually specifying `col_types` (and I think, in general, that's a better strategy when you're reading files with a predefined format).

I'm about to submit to CRAN today, so you might want to prepare a fix in the near future. Apologies for not spotting this earlier - I'm not sure why it didn't crop up when I did the previous round of revdep checks.

**Comment by rich-iannone** [comment]
Thanks for running the tests and pointing this out! I'll use `col_types` and manually specify the types. I'll resubmit to CRAN in a day or two (once `readr` is updated on CRAN).

**Comment by rich-iannone** [comment]
Updated now. Thanks @hadley.
