### ISSUE TITLE
get_isd_station_data drops

### ISSUE THREAD

**Issue by salauer** [rich-iannone/stationaRy#17]
I'm running a loop that grabs a bunch of weather stations, one after another, pulls the data, and binds the rows into one huge data frame. The loop goes smoothly, but then will just freeze on a random year/weather station. Each time I run it, it will stop at a different point, sometimes on the first station in the loop, sometimes (agonizingly) on the last. It will merely show me the last (next?) attempted download:

`trying URL 'ftp://ftp.ncdc.noaa.gov/....'`

and just hang forever. FWIW, this is what happens when I try on my office computer, which is still running Mac OSX Mavericks, R 3.2.3, and all of the latest associated packages (as of 2016-03-07). I'm downloading data from Southeast Asia (Cambodia, Laos, Singapore, Taiwan, Philippines, Malaysia).

In the same problem but a different situation (potentially a separate issue), I gave this a try on my home laptop, which is running Mac OSX El Capitan. Whenever I try to pull data I get the attached error message.
![stationary-error-message](https://cloud.githubusercontent.com/assets/5013117/13586823/54c81020-e491-11e5-8583-0ecbe086e4d2.png)

 It's like it can't even connect to the server, but my internet works for everything else. Perplexing.

Is the github version the same as the CRAN version? Both appear to give the same errors. If so, I may fork and fiddle to see if I can get something that works.

Thanks for making this program, it has been immensely helpful.

**Comment by salauer** [comment]
Tried again today on my office computer. So far it has pulled 24 years off of several hundred stations with no drops yet. I think the connection at my office is pretty good, perhaps there was something being done over at NCDC that was causing the drops.

Still doesn't work on my home computer though. Maybe it doesn't work with one of the latest editions of a particular package.

**Comment by rich-iannone** [comment]
Hi Stephen, The GitHub version is very close to the CRAN version. I've had occasional problems with the FTP server connections but none lately (I'm also running the latest version of OS X El Capitan).

Could you send me a bit of the code that doesn't run on the home computer? I'll see if I can reproduce the error. That it doesn't work on a different computer would indicate that it's not the NOAA server, but something else that's causing the errors.

Thanks!

**Comment by salauer** [comment]
`get_isd_station_data(station_id = "489620-99999", startyear = 1992, endyear = 2016)`

Although honestly, I can't get it to run for any station_id.

**Comment by rich-iannone** [comment]
Stephen, I'm able to replicate the issue. The downloader no longer ignores non-existent files (e.g., there is no data for station `489620-9999` during 1992). Something must have changed with curl or some other underlying component. 

I'll have to make this more robust and have better/safer checking of files. For now, use the work computer!

**Comment by salauer** [comment]
Okay, that helps my sanity a bit! Thanks!
