### ISSUE TITLE
Error message when running loop

### ISSUE THREAD

**Issue by ethanewe** [rich-iannone/stationaRy#20]
Hi, 

I'm attempting to get station data using get_isd_station. Here's part of my loop:
      
#########################
assign(paste(id, "_data", sep=""), get_isd_station_data(station_id = id, 
                                                                 startyear = year(start), 
                                                                  endyear = year(end)))
          
          #Collecting data for time period
          temp_station <- get(paste(id, "_data", sep="")) %>%
            dplyr::mutate(date = ymd(paste(year, month, day, sep="-"))) %>%
            dplyr::filter(date >= start, date <= end) %>%
            as.data.frame()

##########################
but I get the following error message:

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1980/946720-99999-1980.gz'
downloaded 31 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1981/946720-99999-1981.gz'
downloaded 34 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1982/946720-99999-1982.gz'
downloaded 31 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1983/946720-99999-1983.gz'
downloaded 33 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1984/946720-99999-1984.gz'
downloaded 33 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1949/037720-99999-1949.gz'
downloaded 258 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1950/037720-99999-1950.gz'
downloaded 263 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1951/037720-99999-1951.gz'
downloaded 262 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1952/037720-99999-1952.gz'
downloaded 261 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1971/911820-22521-1971.gz'
downloaded 100 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1972/911820-22521-1972.gz'
downloaded 103 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1973/911820-22521-1973.gz'
downloaded 201 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1974/911820-22521-1974.gz'
downloaded 228 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/1975/911820-22521-1975.gz'
downloaded 218 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2002/747043-99999-2002.gz'
downloaded 117 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2003/747043-99999-2003.gz'
downloaded 117 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2004/747043-99999-2004.gz'
downloaded 122 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2005/747043-99999-2005.gz'
downloaded 125 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2006/747043-99999-2006.gz'
Error in if (file.info(file.path(temp_folder, data_file_to_download))$size >  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In download.file(url, ...) : InternetOpenUrl failed: ''
###########################
Some files are OK but I was not able to download from station 747043-99999. Would anyone be able to help?

**Comment by ethanewe** [comment]
The issue is apparently caused by missing year. How do I solve that?

**Comment by rich-iannone** [comment]
@ethanewe This should be resolved now in the latest dev version.
