### ISSUE TITLE
Mistake in AJ1 identifiers in README table

### ISSUE THREAD

**Issue by grantmcdermott** [rich-iannone/stationaRy#21]
Minor issue, but I believe the individual snow ("AJ1") identifiers in the README table are incorrect. They should run from 1-6 not 6-11, i.e.:

Category | Identifier | Column Name
---|---|---
`...` | `...` | `...`
`AJ1` | `aj1_1` | `aj1_snow_depth_dimension`
`AJ1` | `aj1_2` | `aj1_snow_depth_condition_code`
`AJ1` | `aj1_3` | `aj1_snow_depth_quality_code`
`AJ1` | `aj1_4` | `aj1_snow_depth_equiv_water_depth_dimension`
`AJ1` | `aj1_5` | `aj1_snow_depth_equiv_water_condition_code`
`AJ1` | `aj1_6` | `aj1_snow_depth_equiv_water_quality_code`

**Comment by rich-iannone** [comment]
@grantmcdermott sorry it took this long to fix this (almost a year!) but it is now fixed. Thanks for reporting!
