### ISSUE TITLE
Issue pulling in data with get_ncdc_station_data

### ISSUE THREAD

**Issue by sinclairjesse** [rich-iannone/stationaRy#4]
Trying to work through your examples, I get an error 

``` r
library(stationaRy)
library(pipeR)

tofino_airport_2005_2010 <- 
  get_ncdc_station_info() %>>%
    select_ncdc_station(name = "tofino", number = 1) %>>%
    get_ncdc_station_data(startyear = 2005, endyear = 2010)
```

Error in col_positions$begin : $ operator is invalid for atomic vectors

I get the same error when working through the other examples as well. I've run each line in the example above separately, and have no issues pulling in the station info.

EDIT/UPDATE: I reinstalled stationaRy using `install.packages("stationaRy")`rather than though github (using `devtools::install_git("rich-iannone/stationaRy")`) and now I can pull in the data properly.

Thoughts?

**Comment by rich-iannone** [comment]
Okay, thanks for the update. I just ran the CRAN version and had no problem. I'll test and determine what's happening with the GitHub version.

**Comment by rich-iannone** [comment]
I've updated the GitHub version of the package. The source of the error in a misuse of the `read_fwf` function. It's now fixed but there is still some issues with time zone determinations for a significant portion of sites.
