### ISSUE TITLE
`Return` section in documentation

### ISSUE THREAD

**Issue by nutterb** [rich-iannone/stationaRy#7]
It would be nice if the documentation of `get_isd_station_data` had a description of what the vectors in the resulting data frame represent.  I may not be very good at troubleshooting some of the problems I find, but if it's okay with you, I can at least make some contribution in writing out some of this documentation.

For reference, the appropriate source information on this is, I believe,
http://www1.ncdc.noaa.gov/pub/data/ish/ish-format-document.pdf

**Comment by rich-iannone** [comment]
Yes, that was definitely lacking but I would certainly appreciate your help with that documentation!

**Comment by nutterb** [comment]
Great!  I always feel bad when I find problems that I have no idea how to fix.  I'm glad there's something I can do to help.

**Comment by nutterb** [comment]
In `get_isd_stations`, I'm not really sure what the difference between `country` and `country_code` is.  And I couldn't find a document like the one in my initial comment to describe the station data.  So most of the documentation on that function is guess work on my part.  

The most suspect fields are `country`, `country_code`, `gn_gmtoffset`, and `raw_offset`.

In `get_isd_station_data`, `min` and `minute` seem like they might be duplicates.  Otherwise, those descriptions are adaptations from the source document.

**Comment by rich-iannone** [comment]
`country` is from the original stations info file obtained from NCEI. Those other objects are from a GeoNames data collection script I used to get time zone GMT offsets based on lat/lon values. I wanted to know if the country differed between the two data sources. I'm going to clean this up and include the country name, the 2-letter country code, and drop the raw offset value. I'll rename the remaining objects to be more succinct/descriptive. 

By the way, thanks for the great work in that PR!
