### ISSUE TITLE
Not clear that local_tz is being implemented

### ISSUE THREAD

**Issue by pssguy** [rich-iannone/stationaRy#8]
This is for the West Vancouver station which has gn_gmtoffset and rawoffsets of -8

```
get_isd_station_data("717840-99999", startyear=2014,endyear= 2015) %>% 
filter(year==2015&month==1&day==26&!is.na(temp)) %>% 
  select(year,day,hour,temp)

   year day hour temp
1  2015  26    0 12.3
2  2015  26    0 12.3
3  2015  26    1 11.2
4  2015  26    2 10.2
5  2015  26    3  9.8
6  2015  26    4  9.3
7  2015  26    5  9.0
8  2015  26    6  8.0
9  2015  26    6  8.0
10 2015  26    7  8.0
```

I figure the hour=0 temp (for which BTW there are two values which are not always the same) is the 4pm reading of the 25th

Applying local_tz = FALSE 

```
get_isd_station_data("717840-99999", startyear=2014,endyear= 2015,local_tz = FALSE) %>% 
filter(year==2015&month==1&day==26&!is.na(temp)) %>% 
  select(year,day,hour,temp)
```

produces the same output

**Comment by rich-iannone** [comment]
This currently needs to be revised. The idea is to apply an offset (every station now has a value) and shift the value to local time. The `local_tz` argument is a remnant of a workaround for when GMT offsets could not be obtained. Right now I apply the offset to the POSIXct time, however, I've incorrectly filtered the results (filtering by the `year` value, which is clearly wrong for some values after applying the offset).

What I'm going to do now is filter by the POSIXct date and regenerate the time component values (i.e., the year, month, day, etc.). I'll likely keep the `local_tz` in and set to `TRUE` by default, but I'll make sure it functions correctly.

**Comment by pssguy** [comment]
Excellent
