### ISSUE TITLE
Missing years

### ISSUE THREAD

**Issue by pssguy** [rich-iannone/stationaRy#9]
It is no big deal but do you have any idea why some years are missing from some stations

e.g Dawson Creek, BC

```
get_isd_station_data("717840-99999", startyear=2010,endyear= 2013)
trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2010/717840-99999-2010.gz'
downloaded 249 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2011/717840-99999-2011.gz'
trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2012/717840-99999-2012.gz'
trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2013/717840-99999-2013.gz'
downloaded 272 KB

trying URL 'ftp://ftp.ncdc.noaa.gov/pub/data/noaa/2014/717840-99999-2014.gz'
downloaded 304 KB
```

It seems a bit unlikely that there was no data during the 2010/11  - although I note that there was a  nearby station which has begin=2007 and end=2013

**Comment by rich-iannone** [comment]
This sort of thing can and does happen. I've recently collected data from a station that has about 10 years with no data collection. It can be inconsistent. However, I might include that there are such breaks when I implement a station summary feature.
